"""empty message

Revision ID: 94ef0a25506b
Revises: bef9b19f4423
Create Date: 2018-10-26 10:09:44.116763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ef0a25506b'
down_revision = 'bef9b19f4423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('user1_id', sa.Integer(), nullable=False))
    op.add_column('friends', sa.Column('user2_id', sa.Integer(), nullable=False))
    op.drop_constraint('friends_element1_id_fkey', 'friends', type_='foreignkey')
    op.drop_constraint('friends_element2_id_fkey', 'friends', type_='foreignkey')
    op.create_foreign_key(None, 'friends', 'users', ['user1_id'], ['id'])
    op.create_foreign_key(None, 'friends', 'users', ['user2_id'], ['id'])
    op.drop_column('friends', 'element1_id')
    op.drop_column('friends', 'element2_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('element2_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('friends', sa.Column('element1_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.create_foreign_key('friends_element2_id_fkey', 'friends', 'users', ['element2_id'], ['id'])
    op.create_foreign_key('friends_element1_id_fkey', 'friends', 'users', ['element1_id'], ['id'])
    op.drop_column('friends', 'user2_id')
    op.drop_column('friends', 'user1_id')
    # ### end Alembic commands ###
