"""empty message

Revision ID: bef9b19f4423
Revises: 649e61f7d5d9
Create Date: 2018-10-25 14:59:43.308221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef9b19f4423'
down_revision = '649e61f7d5d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('element1_id', sa.Integer(), nullable=False))
    op.add_column('friends', sa.Column('element2_id', sa.Integer(), nullable=False))
    op.drop_constraint('friends_user2_id_fkey', 'friends', type_='foreignkey')
    op.drop_constraint('friends_user1_id_fkey', 'friends', type_='foreignkey')
    op.create_foreign_key(None, 'friends', 'users', ['element1_id'], ['id'])
    op.create_foreign_key(None, 'friends', 'users', ['element2_id'], ['id'])
    op.drop_column('friends', 'user1_id')
    op.drop_column('friends', 'user2_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('user2_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('friends', sa.Column('user1_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.create_foreign_key('friends_user1_id_fkey', 'friends', 'users', ['user1_id'], ['id'])
    op.create_foreign_key('friends_user2_id_fkey', 'friends', 'users', ['user2_id'], ['id'])
    op.drop_column('friends', 'element2_id')
    op.drop_column('friends', 'element1_id')
    # ### end Alembic commands ###
